---
- name: get epgstation
  git:
    repo: https://github.com/l3tnun/EPGStation.git
    dest: /opt/epgstation
    clone: yes

- name: check node_modules
  stat:
    path: /opt/epgstation/node_modules
  register: modules_dir
  changed_when: no

- name: npm install
  command:
    cmd: npm install
    chdir: /opt/epgstation
  when: not modules_dir.stat.exists

- name: check build directory
  stat:
    path: /opt/epgstation/dist
  register: build_dir
  changed_when: no

- name: npm run build
  command:
    cmd: npm run build
    chdir: /opt/epgstation
  when: not build_dir.stat.exists

- name: copy config
  template:
    src: config.json.j2
    dest: /opt/epgstation/config/config.json

- name: copy other config
  copy:
    src: "/opt/epgstation/config/{{ item }}.sample.json"
    dest: "/opt/epgstation/config/{{ item }}.json"
    remote_src: yes
  with_items:
    - operatorLogConfig
    - serviceLogConfig

- name: check pm2
  command: pm2 list
  register: pm2_status
  changed_when: no

- name: start epgstatin
  command:
    cmd: pm2 start dist/server/index.js --name "epgstation-app"
    chdir: /opt/epgstation
  when: '"epgstation-app" not in pm2_status.stdout'

- name: start epgstatin save
  command:
    cmd: pm2 save
    chdir: /opt/epgstation
  when: '"epgstation-app" not in pm2_status.stdout'
