---
- hosts: all
  vars_files:
    - vars/{{ stage }}.yml
  become: yes
  roles:
    - { role: "basic", tag: "basic" }
    - { role: "pxs1ud", tag: "pxs1ud" }
    - { role: "mirakurun", tag: "mirakurun" }
    - { role: "setting", tag: "setting" }
    - { role: "epgstation", tag: "epgstation" }
