---
- hosts: all
  vars_files:
    - vars/{{ stage }}.yml
  become: yes
  roles:
    - { role: "basic", tag: "basic" }
    - { role: "mirakurun", tag: "mirakurun" }
    - { role: "epgstation", tag: "epgstation" }
