---
- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

- name: Install a list of packages
  apt:
    pkg:
      - build-essential
      - curl
      - git
      - vainfo
      - python-dev
    state: latest
    update_cache: yes

- name: Install ffmpeg
  snap:
    name: ffmpeg
    channel: latest/edge

- name: check node
  command: which node
  register: check_node
  ignore_errors: yes
  changed_when: no

- name: download setup_nodejs
  get_url:
    url: https://deb.nodesource.com/setup_12.x
    dest: /tmp/setup_nodejs.sh
  when: check_node is failed

- name: setup nodejs
  command: sh /tmp/setup_nodejs.sh
  when: check_node is failed

- name: cleanup setup_nodejs
  file:
    path: /tmp/setup_nodejs.sh
    state: absent
  when: check_node is failed

- name: Install nodejs
  apt:
    pkg:
    - nodejs
    state: latest
    update_cache: yes
  when: check_node is failed

- name: check pm2
  command: which pm2
  register: check_pm2
  ignore_errors: yes
  changed_when: no

- name: Install "pm2" node.js package.
  npm:
    name: pm2
    global: yes
  when: check_pm2 is failed

- name: pm2 startup
  command: pm2 startup
  when: check_pm2 is failed
